/*CRIAR UM RELATORIO QUE CONTENHAS AS SEGUINTES INFORMACOES:
NOME COMPLETO DO CLIENTE, CONTATO (NOME), ANO E MÊS (1996-08), QUANTIDADE DE COMPRAS NO MÊS, VALOR UNITÁRIO, VALOR TOTAL, STATUS

USAREMOS AS SEGUINTES TABELAS:
TB_CLIENTE, TB_PEDIDO, TB_DETALHE_PEDIDO
*/

SELECT	C2.NomeCompleto,
		C2.Cargo,
		C2.Contato,
		C2.ANO_MES,
		C2.QTD,
		C2.PRECO, C2.VALOR_TOTAL,
		CASE
			WHEN C2.VALOR_TOTAL >= 5000
				THEN	'ATINGIU A META'
			ELSE
						'NAO ATINGIU A META'
		END AS STATUS
	
			FROM	(SELECT	C.NomeCompleto,
							C.Contato,
							C.Cargo,
							C1.ANO_MES,
							C1.QTD,
							C1.PRECO,
							C1.VALOR_TOTAL	
							
					FROM	(SELECT	P.ClienteId, 
									SUBSTRING(CONVERT(VARCHAR, P.DataPedido,120),1,7) AS ANO_MES,
									SUM(D.Quantidade) AS QTD,
									SUM(D.Preco) AS PRECO,
									SUM(D.Quantidade) * SUM(D.Preco) AS VALOR_TOTAL
							FROM TB_DETALHE_PEDIDO D
							JOIN TB_PEDIDO P 
								ON P.NumeroPedido = D.NumeroPedido
							GROUP BY P.ClienteId, SUBSTRING(CONVERT(VARCHAR, P.DataPedido,120),1,7)) AS C1
					JOIN TB_CLIENTE C ON C1.ClienteId = C.ClienteId	) C2